version: "3.8"

services:
  secilstore:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=${API_BASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    restart: always
